# Generated by Django 4.2.11 on 2024-06-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
