# Generated by Django 4.2.11 on 2024-06-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacilityManagement',
        ),
    ]
