# Generated by Django 4.2.11 on 2024-06-25 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('head_app', '0001_initial'),
        ('patient_app', '0002_delete_facilitymanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingstatement',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_statements', to='head_app.appointment'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
