# Generated by Django 4.2.11 on 2024-06-25 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0004_delete_billingstatement'),
        ('accounts_app', '0003_customuser_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='patients',
        ),
        migrations.AddField(
            model_name='customuser',
            name='patients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customuser_patients', to='patient_app.patient'),
            preserve_default=False,
        ),
    ]
