# Generated by Django 4.2.11 on 2024-06-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0004_delete_billingstatement'),
        ('accounts_app', '0004_remove_customuser_patients_customuser_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='patients',
        ),
        migrations.AddField(
            model_name='customuser',
            name='patients',
            field=models.ManyToManyField(related_name='customuser_patients', to='patient_app.patient'),
        ),
    ]
